spring:
  application:
    name: news-aggregator-service
  output:
    ansi:
      enabled: always # enables ANSI colors in the console output; logging will use colors in the console
  config:
    import:
    - classpath:application-${spring.profiles.active}.yml # imports the profile-specific configuration file based on the active profile
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:DEV}

  datasource:
    url: jdbc:h2:mem:defaultdb
    username: user
    password: pass
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true # enables H2 console for database management
      path: /news-aggregator-h2-console # path to access the H2 console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true # enables SQL logging
    hibernate:
      ddl-auto: update # automatically updates the database schema

server:
  port: 8081


logging:
  level:
    root: INFO # logging level for the spring framework and the libraries it uses

  pattern:
    console: "%d{ISO8601} [%thread] %highlight(%-5level) %class{36}.%method:%line %logger{36} - %msg%n" # pattern for the console logging

  